### PR TITLE
Webpack5 issue

### PR DESCRIPTION
**Pull request by markmaksi74**

### CODE REVIEW

**Comment by markmaksi74** [comment]
Storybook fails to configure webpack version 5.
When I apply the commands from this link: [](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5) it throws errors saying that some packages are missing so I try to install the packages manually from npm but again it fails. How to handle such problems?

**Comment by jakxnz** [comment]
@markmaksi74 can I propose we close this PR?

**Comment by markmaksi74** [comment]
> @markmaksi74 can I propose we close this PR?

I believe yes! But I have a question before we close it.
To update the lock file we have to delete it first, install `storybook/manager-webpack5` and `storybook/manager-webpack5` , and then delete the CRA addon? Is this true?

**Comment by jakxnz** [comment]
> > @markmaksi74 can I propose we close this PR?
> 
> I believe yes! But I have a question before we close it. To update the lock file we have to delete it first, install `storybook/manager-webpack5` and `storybook/manager-webpack5` , and then delete the CRA addon? Is this true?

You don't have to delete the `yarn.lock` to recreate it. Any `yarn add` or `yarn upgrade` will update the `yarn.lock` file.

`storybook/manager-webpack5` and `storybook/manager-webpack5` can be installed at any time, in any order. They're just the dependencies Storybook looks for when Storybook is configured to use Webpack 5.

The CRA addon could have been deleted at any time, but it only started causing issues when we switched from using Webpack 4 to Webpack 5.

**Pull request closed without merging**
